'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class album
    
    '''<summary>
    '''T_albumTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_albumTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GV_tracks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GV_tracks As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''T_titlePop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_titlePop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''T_trackId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_trackId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''T_compPop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_compPop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''T_pubPop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_pubPop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''G_mp3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents G_mp3 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''G_wav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents G_wav As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GridProjectList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridProjectList As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnAddProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddProjects As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''L_titlePlayer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_titlePlayer As Global.System.Web.UI.WebControls.Label
End Class
