'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class musicsearch
    
    '''<summary>
    '''T_mainsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_mainsearch As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''B_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_Search As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DD_style control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_style As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SqlGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlGenre As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DD_tempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_tempo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Sqltempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sqltempo As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''T_keyword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_keyword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BSearch_Genre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BSearch_Genre As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DD_Composer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_Composer As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SqlComposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlComposer As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BSearch_Composer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BSearch_Composer As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DD_Album control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_Album As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SqlAlbum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlAlbum As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''BSearch_Album control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BSearch_Album As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TrackList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrackList As Global.System.Web.UI.WebControls.GridView
End Class
