'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class musicsearch
    
    '''<summary>
    '''T_mainsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_mainsearch As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hfTrackId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTrackId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''B_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_Search As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CheckStyleGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckStyleGenre As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckComposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckComposer As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckAlbum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckAlbum As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LinkButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''DD_style control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_style As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SqlGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlGenre As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DD_tempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_tempo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Sqltempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sqltempo As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btnSearchStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchStyle As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''DD_Composer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_Composer As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SqlComposer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlComposer As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btnSearchComposers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchComposers As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''DD_Album control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_Album As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SqlAlbum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlAlbum As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''btnSearchAlbums control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchAlbums As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LblCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCheck As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCheckAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCheckAll As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOneFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneFilter As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GV_tracks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GV_tracks As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlTrackInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlTrackInfo As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''GridStylesGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridStylesGenre As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GridCDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridCDs As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlCDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlCDs As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''GridComposers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridComposers As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlComposers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlComposers As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
End Class
