'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class project
    
    '''<summary>
    '''B_newFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_newFolder As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''DD_project1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_project1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sqlProyectos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlProyectos As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''GridProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridProjects As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Sqlproject_Grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sqlproject_Grid As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''GridTracksInProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridTracksInProject As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''L_titlePlayer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_titlePlayer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''T_newfolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents T_newfolder As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''B_addfolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents B_addfolder As Global.System.Web.UI.WebControls.Button
End Class
